/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import FalconerPacking.Statement
public import FalconerPacking.Algebra
public import FalconerPacking.HardGapAlgebra
public import FalconerPacking.HardGapCurve
public import FalconerPacking.HardGapThreshold
public import FalconerPacking.Dimensions
public import FalconerPacking.Profile
public import FalconerPacking.UnforcedProfile
public import FalconerPacking.ChainCompression
public import FalconerPacking.HighSlopeProfile
public import FalconerPacking.ProfileInterpolation
public import FalconerPacking.HardPoints
public import FalconerPacking.GapTails
public import FalconerPacking.HardPointChains
public import FalconerPacking.FiniteHardPoints
public import FalconerPacking.HardPointPartition
public import FalconerPacking.RealChainCompression
public import FalconerPacking.RealChainRounding
public import FalconerPacking.HardGapProfile
public import FalconerPacking.FiniteHardGapProfile
public import FalconerPacking.StrictFiniteProfile
public import FalconerPacking.Dyadic
public import FalconerPacking.Energy
public import FalconerPacking.Restriction
public import FalconerPacking.LocalEnergy
public import FalconerPacking.PositiveLimit
public import FalconerPacking.PinnedKernel
public import FalconerPacking.AffineDistance
public import FalconerPacking.DyadicCenters
public import FalconerPacking.MomentCenters
public import FalconerPacking.DyadicMomentCenters
public import FalconerPacking.AngularTruncation
public import FalconerPacking.GaussianEnergy
public import FalconerPacking.GaussianWeightedEnergy
public import FalconerPacking.GaussianFrostman
public import FalconerPacking.GaussianBallEnergy
public import FalconerPacking.GaussianMellin
public import FalconerPacking.RieszFourier1D
public import FalconerPacking.RieszFourier2D
public import FalconerPacking.PolarFourierEnergy
public import FalconerPacking.WeakDensityLimit
public import FalconerPacking.SchwartzDensityCriterion
public import FalconerPacking.FourierDensity
public import FalconerPacking.ProjectionFourier
public import FalconerPacking.ProjectionDensity
public import FalconerPacking.CorrelatedAngles
public import FalconerPacking.CorrelatedFourierShift
public import FalconerPacking.FiniteRegularization
public import FalconerPacking.RegularMeasureProfile
public import FalconerPacking.RegularProfileParameters
public import FalconerPacking.RadialProjectionKernel
public import FalconerPacking.RadialProjectionEnergy
public import FalconerPacking.RadialProjectionTransversality
public import FalconerPacking.RadialProjectionTraceWeight
public import FalconerPacking.RadialProjectionRay
public import FalconerPacking.RadialProjectionLine
public import FalconerPacking.RadialProjectionTrace
public import FalconerPacking.RadialProjectionLevelSet
public import FalconerPacking.RadialProjectionWeakMoment
public import FalconerPacking.SmoothProjectionDensity
public import FalconerPacking.SmoothMeasureApproximation
public import FalconerPacking.SmoothProbabilityApproximation
public import FalconerPacking.RadialProjectionSmoothTrace
public import FalconerPacking.RadialProjectionAngularMoment
public import FalconerPacking.WeightedBandEnergy
public import FalconerPacking.AngularDerivativeEnergy
public import FalconerPacking.DyadicBandSum
public import FalconerPacking.DyadicBandIntegral
public import FalconerPacking.CorrelatedBandEnergy
public import FalconerPacking.CorrelatedFourierEnergy
public import FalconerPacking.ProjectionDensityComparison
public import FalconerPacking.RadialAngleGeometry
public import FalconerPacking.CorrelatedAngularCharts
public import FalconerPacking.UniformFourierBands
public import FalconerPacking.UniformProjectionEnergy
public import FalconerPacking.Extraction
public import FalconerPacking.Content
public import FalconerPacking.FrostmanWeights
public import FalconerPacking.WeightMeasure
public import FalconerPacking.OccupiedCubes
public import FalconerPacking.WeakLimit
public import FalconerPacking.FrostmanLimit
public import FalconerPacking.CompactReduction
public import FalconerPacking.BorelFrostman
public import FalconerPacking.Capacity
public import FalconerPacking.GeometricCapacity
public import FalconerPacking.DyadicCapacity
public import FalconerPacking.DyadicContentComparison
public import FalconerPacking.BorelCompactReduction
public import FalconerPacking.LaminarContent
public import FalconerPacking.PinnedMeasure
public import FalconerPacking.Main

public import FalconerPacking.AffineProjectionGeometry
public import FalconerPacking.LocalProjectionL1
public import FalconerPacking.RadialProjectionSmoothBound
public import FalconerPacking.FrostmanLineNull
public import FalconerPacking.SmoothApproximationTests
public import FalconerPacking.WeakMomentLimit

public import FalconerPacking.AffineDistanceL1
public import FalconerPacking.RadialProjectionAngularShift
public import FalconerPacking.RadialProjectionSmoothMoment
public import FalconerPacking.WeakMomentDensity
public import FalconerPacking.RadialProjectionWeakLimit
public import FalconerPacking.RadialProjectionJointDensity
public import FalconerPacking.RadialMomentCenters

public import FalconerPacking.AffineDistanceTruncation
public import FalconerPacking.RadialProjectionApproximationMoment
public import FalconerPacking.RadialProjectionTheorem
public import FalconerPacking.DyadicComparisonSums

public import FalconerPacking.CoherentBorelParameters
public import FalconerPacking.DyadicPositiveCubes
public import FalconerPacking.DyadicAffineDensity

public import FalconerPacking.CoherentStepSummability

public import FalconerPacking.DyadicAffineGeometry
public import FalconerPacking.CoherentDyadicStep
public import FalconerPacking.CoherentCompactTheorem
public import FalconerPacking.CoherentBorelTheorem
public import FalconerPacking.DistancePolarDensity
public import FalconerPacking.PinnedPositiveComponent
public import FalconerPacking.BallOverlap
public import FalconerPacking.FiniteFourierOrthogonality
public import FalconerPacking.RadialFourierAverage
public import FalconerPacking.TruncatedConditionalEnergy
public import FalconerPacking.WeakDomination
public import FalconerPacking.WeightedConvolutionEmbedding
public import FalconerPacking.LocalizedFourierOrthogonality
public import FalconerPacking.BandlimitedCutoff
public import FalconerPacking.RadialPlancherel
public import FalconerPacking.CircularPlancherel
public import FalconerPacking.RegularComponentBalls
public import FalconerPacking.RegularConditionalEnergy
public import FalconerPacking.SchwartzReproducingKernel
public import FalconerPacking.LiuPinnedIdentity
public import FalconerPacking.CircleFourierConvolution
public import FalconerPacking.ComplexDistancePushforward
public import FalconerPacking.AngularHeavyCells
public import FalconerPacking.RadialHeavyCells
public import FalconerPacking.TubePairCounting
public import FalconerPacking.AnisotropicSchwartzKernel
public import FalconerPacking.OrientedReproducingKernel
public import FalconerPacking.SchwartzPotential
public import FalconerPacking.GridMassGrowth
public import FalconerPacking.AnisotropicKernelPotential
public import FalconerPacking.ScaledBandlimitedCutoff

public import FalconerPacking.CutoffEnergyLocalization
public import FalconerPacking.SelectedLocalEnergy
public import FalconerPacking.SelectedTubeWeights
public import FalconerPacking.SelectedTubeGeometry
public import FalconerPacking.EnlargedGridSquares
public import FalconerPacking.SlopeStripGeometry
public import FalconerPacking.SlopeTubeEnergy
public import FalconerPacking.SlopeTubeNet
public import FalconerPacking.AnnularDensityLimit

public import FalconerPacking.CircleBallMass
public import FalconerPacking.CircleCapGeometry
public import FalconerPacking.CircleSpectralConvolution
public import FalconerPacking.CompactSourceSchwartz
public import FalconerPacking.DyadicAnnularKernel
public import FalconerPacking.InitialFourierLocalization
public import FalconerPacking.SchwartzMeasureReconstruction
public import FalconerPacking.SelectedCapEnergySums
public import FalconerPacking.SelectedCapGeometry
public import FalconerPacking.SelectedCapEmbedding

public import FalconerPacking.TerminalCircleEnergy
public import FalconerPacking.CircleSpectralSchwartz
public import FalconerPacking.CompactAnnularReconstruction
public import FalconerPacking.AnnularPinnedReconstruction
public import FalconerPacking.SelectedCapCoefficients
public import FalconerPacking.SelectedCapGridEmbedding
public import FalconerPacking.SelectedCapNormalized
public import FalconerPacking.InheritedFourierLabels
public import FalconerPacking.FiniteEnergyIteration
public import FalconerPacking.SmoothStripPartition

public import FalconerPacking.AngularGridGeometry
public import FalconerPacking.OverlappingHeavyCells
public import FalconerPacking.EnlargedAngularCells
public import FalconerPacking.WitnessedTubeDeletion
public import FalconerPacking.SourceTubeMass
public import FalconerPacking.SelectedCapSpectralWidth
public import FalconerPacking.SelectedCapSpectralNormalized
public import FalconerPacking.CircleCellSchwartz
public import FalconerPacking.CircleCellSupport
public import FalconerPacking.CircleCellTerminal
public import FalconerPacking.PlanarStripPackets
public import FalconerPacking.SourceStripPartition
public import FalconerPacking.RadialAngleChart
public import FalconerPacking.StripRadialContainment
public import FalconerPacking.CircularPhase
public import FalconerPacking.NonstationaryPhase
public import FalconerPacking.NonstationaryPhaseBounds
public import FalconerPacking.RegularizedReciprocal
public import FalconerPacking.AngularCapWeights
public import FalconerPacking.SmoothAngularCaps

public import FalconerPacking.SeparatedBallGeometry
public import FalconerPacking.SeparatedBallMeasures
public import FalconerPacking.CircularReciprocal
public import FalconerPacking.SourceWavePackets
public import FalconerPacking.LocalizedPacketMass

public import FalconerPacking.PacketDirectionCounting
public import FalconerPacking.PacketPairMultiplicity
public import FalconerPacking.SourceWavePacketMass
public import FalconerPacking.DeletedPacketSum
public import FalconerPacking.DyadicAngularCaps
public import FalconerPacking.AngularBumpDerivatives
public import FalconerPacking.NormalizedAngularDerivatives
public import FalconerPacking.CircularPacketAmplitude

public import FalconerPacking.AnisotropicDirectionProfile

public import FalconerPacking.PacketDeletionMass

public import FalconerPacking.AngularGridRefinement
public import FalconerPacking.CapLabelGeometry
public import FalconerPacking.StandardCapLabelData
public import FalconerPacking.StandardCapCircleSchwartz
public import FalconerPacking.CoarseCapCircleSupport
public import FalconerPacking.ActiveCapCircleTree
public import FalconerPacking.SmoothPeriodicUnfolding
public import FalconerPacking.FullCirclePacketDecay

public import FalconerPacking.UniformSchwartzFourier
public import FalconerPacking.UniformSchwartzTails
public import FalconerPacking.RescaledSchwartzKernel
public import FalconerPacking.StandardAngularGrid
public import FalconerPacking.LocalCompositionBounds
public import FalconerPacking.RescaledAngularDerivatives
public import FalconerPacking.CapFrequencyRescaling
public import FalconerPacking.RescaledAnnularFactor
public import FalconerPacking.UniformDyadicCapSymbols
public import FalconerPacking.DyadicCapKernelBounds
public import FalconerPacking.SourcePacketFrequency
public import FalconerPacking.RemotePinnedPacket

public import FalconerPacking.CircleCapScaledGeometry
public import FalconerPacking.InheritedFineCapSupport
public import FalconerPacking.SelectedFineCapEmbedding
public import FalconerPacking.PhysicalDyadicCapKernels
public import FalconerPacking.StandardCapKernelBounds
public import FalconerPacking.DyadicPacketDeletion

public import FalconerPacking.CircleCapChordGeometry
public import FalconerPacking.InheritedCoarseCapSupport
public import FalconerPacking.SelectedCoarseCapEmbedding
public import FalconerPacking.NormalizedSpatialStrip
public import FalconerPacking.SpatialStripFourier
public import FalconerPacking.ScaledFourierBallEnergy
public import FalconerPacking.JointPinnedCircleEnergy
public import FalconerPacking.FiniteTubeEnlargement
public import FalconerPacking.EnlargedSlopeTubes
public import FalconerPacking.SlopeNormalChart
public import FalconerPacking.EnlargedSlopeTubeGeometry
public import FalconerPacking.SlopeTubeCoverage

public import FalconerPacking.CircleEnergyIntegration
public import FalconerPacking.PinnedShellL2
public import FalconerPacking.OmittedCircleEnergy
public import FalconerPacking.DyadicCapAncestry
public import FalconerPacking.MarkedDyadicCircle
public import FalconerPacking.SourcePacketFourierConvolution
public import FalconerPacking.SourcePacketMicrolocal
public import FalconerPacking.SlopeTubeNormals
public import FalconerPacking.EnlargedSlopeTubeDeletion
public import FalconerPacking.SchwartzRadialTails
public import FalconerPacking.PhysicalCapRadialTails
public import FalconerPacking.SourceCutoffError

public import FalconerPacking.AngularSpectralSelector
public import FalconerPacking.AngularSpectralWindowBounds
public import FalconerPacking.DyadicAnnularSummability
public import FalconerPacking.AnnularPinnedDensity
public import FalconerPacking.FiniteEnergyIterationENNReal
public import FalconerPacking.InheritedEnergyPartition
public import FalconerPacking.SelectedCapParentEmbedding
public import FalconerPacking.SelectedCircleParentEdges
public import FalconerPacking.DyadicCircleIdentification
public import FalconerPacking.DyadicGridEdgeGeometry
public import FalconerPacking.MarkedCircleParentEdge
public import FalconerPacking.DyadicSourceCutoffError
public import FalconerPacking.SlopeTubeSourceCoverage
public import FalconerPacking.AllDirectionTubeDeletion
public import FalconerPacking.SpectralCircleKernel
public import FalconerPacking.SpectralPacketFubini
public import FalconerPacking.RemoteSpectralPacket

public import FalconerPacking.SourceCutoffSpectrum
public import FalconerPacking.PacketEffectiveNormals
public import FalconerPacking.PhysicalDyadicMarks
public import FalconerPacking.PhysicalMarkedPairs
public import FalconerPacking.DyadicChainCubes
public import FalconerPacking.MarkedCircleChain
public import FalconerPacking.SpectralCircleLinearity
public import FalconerPacking.InitialSpectralReconstruction

public import FalconerPacking.PhysicalBadPacketPairs

public import FalconerPacking.AngularMeshChoice
public import FalconerPacking.EnlargedTruncatedEnergy
public import FalconerPacking.ProfileMarginParameters
public import FalconerPacking.StrictShellParameters
public import FalconerPacking.InheritedCapMultiplier
public import FalconerPacking.InheritedCircleEnergy
public import FalconerPacking.GridEnergyBounds
public import FalconerPacking.MarkedCircleEnergyBounds
public import FalconerPacking.MarkedCircleFourierChain

public import FalconerPacking.PhysicalBadPacketBounds
public import FalconerPacking.PhysicalChainScales
public import FalconerPacking.ConditionalAngularThreshold
public import FalconerPacking.PhysicalConditionalDeletion
public import FalconerPacking.PhysicalDeletionGeometry
public import FalconerPacking.MarkedCircleInitialLocalization
public import FalconerPacking.MarkedCircleInitialSum
public import FalconerPacking.ProfileChainSequences
public import FalconerPacking.ProfileChainPhysicalScales
public import FalconerPacking.WeightedConditionalDeletion
public import FalconerPacking.InheritedPacketDeletion
public import FalconerPacking.InheritedPacketL1
public import FalconerPacking.DyadicSpectralNorms
public import FalconerPacking.DyadicInitialReconstruction
public import FalconerPacking.InitialCellRemoteGeometry
public import FalconerPacking.InitialPacketDecomposition

public import FalconerPacking.PhysicalDeletionConstants
public import FalconerPacking.RegularPartitionInitialLoss
public import FalconerPacking.SourceTubeMassAE
public import FalconerPacking.TubeDeletionAE
public import FalconerPacking.PhysicalDeletionAE
public import FalconerPacking.BroadCircleOverlap
public import FalconerPacking.BroadSelectedCircleParents
public import FalconerPacking.BroadMarkedCircleEdge
public import FalconerPacking.BroadMarkedCircleChain
public import FalconerPacking.BroadMarkedCircleFourierChain
public import FalconerPacking.BlockProfileChainScales

public import FalconerPacking.DyadicRootRestriction
public import FalconerPacking.SeparatedDyadicData
public import FalconerPacking.DisjointComponentDensities
public import FalconerPacking.AnnularRemainder
public import FalconerPacking.AnnularComponentGluing
public import FalconerPacking.EventualAnnularCriterion
public import FalconerPacking.PacketAnnularIdentity
public import FalconerPacking.RegularPhysicalDeletion
public import FalconerPacking.UniformPhysicalDeletion
public import FalconerPacking.UniformInheritedPacketL1
public import FalconerPacking.InitialCircleMultiplier
public import FalconerPacking.InitialCircleMultiplierRadius
public import FalconerPacking.MarkedStandardReconstruction
public import FalconerPacking.InitialRetainedEnergy
public import FalconerPacking.RetainedCircleChain
public import FalconerPacking.ChainThresholdProduct
public import FalconerPacking.ChainThresholdDecay
public import FalconerPacking.ChainEnergyRemainders
public import FalconerPacking.ChainEnergyDecay
public import FalconerPacking.PaddedProfileChain
public import FalconerPacking.PaddedChainDecay

public import FalconerPacking.AnnularScaleSchedule
public import FalconerPacking.SourcePacketRadialTail
public import FalconerPacking.DyadicPacketRadialTail
public import FalconerPacking.RetainedOmittedCircleEnergy
public import FalconerPacking.DyadicDeletionCoefficients
public import FalconerPacking.DyadicDeletionDecay
public import FalconerPacking.InheritedShellDecay
public import FalconerPacking.RegularInheritedEnergy
public import FalconerPacking.RetainedShellRemainder
public import FalconerPacking.DyadicSchwartzFamily
public import FalconerPacking.RetainedPinFamily
public import FalconerPacking.RetainedCircleIntegration

public import FalconerPacking.AnnularDecayAssembly
public import FalconerPacking.ComponentAnnularCriterion
public import FalconerPacking.HardGapBorelData
public import FalconerPacking.RegularShellParameters
public import FalconerPacking.RegularRetainedRemainder
public import FalconerPacking.RetainedDistanceEnergy
public import FalconerPacking.RetainedChainDistance
public import FalconerPacking.RetainedEnergyConstants

public import FalconerPacking.RetainedChainScalarDecay
public import FalconerPacking.RetainedChainConstantBound
public import FalconerPacking.ChainCoefficientMonotone
public import FalconerPacking.RegularDiscardedPins

public import FalconerPacking.RegularChainCoefficient
public import FalconerPacking.RetainedScalarEnergy
public import FalconerPacking.RegularRetainedEnergy
public import FalconerPacking.RegularAnnularComponents
public import FalconerPacking.HausdorffPackingTheorem

/-!
# A Hausdorff–packing criterion for self-pinned distance sets
-/

@[expose] public section
