/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
import FalconerPacking.Statement
import FalconerPacking.Algebra
import FalconerPacking.HardGapAlgebra
import FalconerPacking.HardGapCurve
import FalconerPacking.HardGapThreshold
import FalconerPacking.Dimensions
import FalconerPacking.Profile
import FalconerPacking.UnforcedProfile
import FalconerPacking.ChainCompression
import FalconerPacking.HighSlopeProfile
import FalconerPacking.ProfileInterpolation
import FalconerPacking.HardPoints
import FalconerPacking.GapTails
import FalconerPacking.HardPointChains
import FalconerPacking.FiniteHardPoints
import FalconerPacking.HardPointPartition
import FalconerPacking.RealChainCompression
import FalconerPacking.RealChainRounding
import FalconerPacking.HardGapProfile
import FalconerPacking.FiniteHardGapProfile
import FalconerPacking.StrictFiniteProfile
import FalconerPacking.Dyadic
import FalconerPacking.Energy
import FalconerPacking.Restriction
import FalconerPacking.LocalEnergy
import FalconerPacking.PositiveLimit
import FalconerPacking.PinnedKernel
import FalconerPacking.AffineDistance
import FalconerPacking.DyadicCenters
import FalconerPacking.MomentCenters
import FalconerPacking.DyadicMomentCenters
import FalconerPacking.AngularTruncation
import FalconerPacking.GaussianEnergy
import FalconerPacking.GaussianWeightedEnergy
import FalconerPacking.GaussianFrostman
import FalconerPacking.GaussianBallEnergy
import FalconerPacking.GaussianMellin
import FalconerPacking.RieszFourier1D
import FalconerPacking.RieszFourier2D
import FalconerPacking.PolarFourierEnergy
import FalconerPacking.WeakDensityLimit
import FalconerPacking.SchwartzDensityCriterion
import FalconerPacking.FourierDensity
import FalconerPacking.ProjectionFourier
import FalconerPacking.ProjectionDensity
import FalconerPacking.CorrelatedAngles
import FalconerPacking.CorrelatedFourierShift
import FalconerPacking.FiniteRegularization
import FalconerPacking.RegularMeasureProfile
import FalconerPacking.RegularProfileParameters
import FalconerPacking.RadialProjectionKernel
import FalconerPacking.RadialProjectionEnergy
import FalconerPacking.RadialProjectionTransversality
import FalconerPacking.RadialProjectionTraceWeight
import FalconerPacking.RadialProjectionRay
import FalconerPacking.RadialProjectionLine
import FalconerPacking.RadialProjectionTrace
import FalconerPacking.RadialProjectionLevelSet
import FalconerPacking.RadialProjectionWeakMoment
import FalconerPacking.SmoothProjectionDensity
import FalconerPacking.SmoothMeasureApproximation
import FalconerPacking.SmoothProbabilityApproximation
import FalconerPacking.RadialProjectionSmoothTrace
import FalconerPacking.RadialProjectionAngularMoment
import FalconerPacking.WeightedBandEnergy
import FalconerPacking.AngularDerivativeEnergy
import FalconerPacking.DyadicBandSum
import FalconerPacking.DyadicBandIntegral
import FalconerPacking.CorrelatedBandEnergy
import FalconerPacking.CorrelatedFourierEnergy
import FalconerPacking.ProjectionDensityComparison
import FalconerPacking.RadialAngleGeometry
import FalconerPacking.CorrelatedAngularCharts
import FalconerPacking.UniformFourierBands
import FalconerPacking.UniformProjectionEnergy
import FalconerPacking.Extraction
import FalconerPacking.Content
import FalconerPacking.FrostmanWeights
import FalconerPacking.WeightMeasure
import FalconerPacking.OccupiedCubes
import FalconerPacking.WeakLimit
import FalconerPacking.FrostmanLimit
import FalconerPacking.CompactReduction
import FalconerPacking.BorelFrostman
import FalconerPacking.Capacity
import FalconerPacking.GeometricCapacity
import FalconerPacking.DyadicCapacity
import FalconerPacking.DyadicContentComparison
import FalconerPacking.BorelCompactReduction
import FalconerPacking.LaminarContent
import FalconerPacking.PinnedMeasure
import FalconerPacking.Main

import FalconerPacking.AffineProjectionGeometry
import FalconerPacking.LocalProjectionL1
import FalconerPacking.RadialProjectionSmoothBound
import FalconerPacking.FrostmanLineNull
import FalconerPacking.SmoothApproximationTests
import FalconerPacking.WeakMomentLimit

import FalconerPacking.AffineDistanceL1
import FalconerPacking.RadialProjectionAngularShift
import FalconerPacking.RadialProjectionSmoothMoment
import FalconerPacking.WeakMomentDensity
import FalconerPacking.RadialProjectionWeakLimit
import FalconerPacking.RadialProjectionJointDensity
import FalconerPacking.RadialMomentCenters

import FalconerPacking.AffineDistanceTruncation
import FalconerPacking.RadialProjectionApproximationMoment
import FalconerPacking.RadialProjectionTheorem
import FalconerPacking.DyadicComparisonSums

import FalconerPacking.CoherentBorelParameters
import FalconerPacking.DyadicPositiveCubes
import FalconerPacking.DyadicAffineDensity

import FalconerPacking.CoherentStepSummability

import FalconerPacking.DyadicAffineGeometry
import FalconerPacking.CoherentDyadicStep
import FalconerPacking.CoherentCompactTheorem
import FalconerPacking.CoherentBorelTheorem
import FalconerPacking.DistancePolarDensity
import FalconerPacking.PinnedPositiveComponent
import FalconerPacking.BallOverlap
import FalconerPacking.FiniteFourierOrthogonality
import FalconerPacking.RadialFourierAverage
import FalconerPacking.TruncatedConditionalEnergy
import FalconerPacking.WeakDomination
import FalconerPacking.WeightedConvolutionEmbedding
import FalconerPacking.LocalizedFourierOrthogonality
import FalconerPacking.BandlimitedCutoff
import FalconerPacking.RadialPlancherel
import FalconerPacking.CircularPlancherel
import FalconerPacking.RegularComponentBalls
import FalconerPacking.RegularConditionalEnergy
import FalconerPacking.SchwartzReproducingKernel
import FalconerPacking.LiuPinnedIdentity

/-!
# A Hausdorff–packing criterion for self-pinned distance sets
-/
