/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
import FalconerPacking.Statement
import FalconerPacking.Algebra
import FalconerPacking.HardGapAlgebra
import FalconerPacking.HardGapCurve
import FalconerPacking.HardGapThreshold
import FalconerPacking.Dimensions
import FalconerPacking.Profile
import FalconerPacking.UnforcedProfile
import FalconerPacking.ChainCompression
import FalconerPacking.HighSlopeProfile
import FalconerPacking.ProfileInterpolation
import FalconerPacking.HardPoints
import FalconerPacking.GapTails
import FalconerPacking.HardPointChains
import FalconerPacking.FiniteHardPoints
import FalconerPacking.HardPointPartition
import FalconerPacking.RealChainCompression
import FalconerPacking.RealChainRounding
import FalconerPacking.HardGapProfile
import FalconerPacking.FiniteHardGapProfile
import FalconerPacking.StrictFiniteProfile
import FalconerPacking.Dyadic
import FalconerPacking.Energy
import FalconerPacking.Restriction
import FalconerPacking.LocalEnergy
import FalconerPacking.PositiveLimit
import FalconerPacking.PinnedKernel
import FalconerPacking.AffineDistance
import FalconerPacking.DyadicCenters
import FalconerPacking.MomentCenters
import FalconerPacking.DyadicMomentCenters
import FalconerPacking.AngularTruncation
import FalconerPacking.GaussianEnergy
import FalconerPacking.GaussianWeightedEnergy
import FalconerPacking.GaussianFrostman
import FalconerPacking.GaussianBallEnergy
import FalconerPacking.PolarFourierEnergy
import FalconerPacking.WeakDensityLimit
import FalconerPacking.SchwartzDensityCriterion
import FalconerPacking.FourierDensity
import FalconerPacking.ProjectionFourier
import FalconerPacking.ProjectionDensity
import FalconerPacking.CorrelatedAngles
import FalconerPacking.CorrelatedFourierShift
import FalconerPacking.FiniteRegularization
import FalconerPacking.RadialProjectionKernel
import FalconerPacking.RadialProjectionEnergy
import FalconerPacking.RadialProjectionTransversality
import FalconerPacking.WeightedBandEnergy
import FalconerPacking.AngularDerivativeEnergy
import FalconerPacking.DyadicBandSum
import FalconerPacking.Extraction
import FalconerPacking.Content
import FalconerPacking.FrostmanWeights
import FalconerPacking.WeightMeasure
import FalconerPacking.OccupiedCubes
import FalconerPacking.WeakLimit
import FalconerPacking.FrostmanLimit
import FalconerPacking.CompactReduction
import FalconerPacking.BorelFrostman
import FalconerPacking.Capacity
import FalconerPacking.GeometricCapacity
import FalconerPacking.DyadicCapacity
import FalconerPacking.DyadicContentComparison
import FalconerPacking.BorelCompactReduction
import FalconerPacking.LaminarContent
import FalconerPacking.PinnedMeasure
import FalconerPacking.Main

/-!
# A Hausdorff–packing criterion for self-pinned distance sets
-/
